# Generated by Django 4.2.6 on 2023-10-21 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_students_adress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='Adress',
            new_name='Address',
        ),
    ]
