# Generated by Django 4.2.6 on 2023-10-21 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='recipe_Imge',
            new_name='recipe_Image',
        ),
    ]
